version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      room-toolchain:
        patterns:
          - "androidx.room:*"
          - "com.google.devtools.ksp"
          - "org.jetbrains.kotlin.*"
          - "org.jetbrains.kotlinx:kotlinx-serialization-*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
